import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Clock3, LibraryBig, Search, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { listBooks } from "../services/books";
import { myBorrowRequests } from "../services/borrow";
import { supabase } from "../lib/supabase";
import StatCard from "../components/StatCard";
import BookCard from "../components/BookCard";

export default function Home(){
 const {profile}=useAuth(); const [books,setBooks]=useState([]); const [counts,setCounts]=useState({available:0,borrowed:0,pending:0,resources:0});
 useEffect(()=>{(async()=>{try{const b=await listBooks();setBooks(b.slice(0,4));const req=await myBorrowRequests();const r=await supabase.from("digital_resources").select("id",{count:"exact",head:true});setCounts({available:b.reduce((n,x)=>n+Number(x.available_copies),0),borrowed:req.filter(x=>x.status==="approved").length,pending:req.filter(x=>x.status==="pending").length,resources:r.count||0});}catch{}})()},[]);
 return <div><section className="overflow-hidden rounded-3xl bg-slate-950 px-6 py-12 text-white lg:px-12 lg:py-16"><div className="max-w-3xl"><div className="eyebrow text-teal-300">Student library</div><h1 className="mt-4 text-4xl font-black tracking-tight lg:text-6xl">Welcome, {profile?.full_name?.split(" ")[0]||"Student"} 👋</h1><p className="mt-5 max-w-2xl text-lg text-slate-300">Find your next book, request a copy, and explore digital study resources from one place.</p><Link to="/books" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-teal-400 px-5 py-3 font-bold text-slate-950">Browse books <ArrowRight size={18}/></Link></div></section><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard icon={BookOpen} label="Available Book Copies" value={counts.available}/><StatCard icon={LibraryBig} label="My Borrowed Books" value={counts.borrowed}/><StatCard icon={Clock3} label="Pending Requests" value={counts.pending}/><StatCard icon={Sparkles} label="Digital Resources" value={counts.resources}/></div><section className="mt-10"><div className="flex items-end justify-between"><div><div className="eyebrow">Library shelf</div><h2 className="mt-1 text-2xl font-bold">Recently added books</h2></div><Link to="/books" className="text-sm font-semibold text-teal-700">View all <ArrowRight className="inline" size={15}/></Link></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{books.map(b=><BookCard key={b.id} book={b}/>)}</div>{!books.length&&<div className="card mt-5 p-10 text-center text-slate-500">No books are available yet. An administrator can add the first collection.</div>}</section><section className="mt-12 card flex flex-col items-start justify-between gap-5 p-7 lg:flex-row lg:items-center"><div><div className="eyebrow">Digital learning</div><h2 className="mt-1 text-2xl font-bold">Study beyond the shelves.</h2><p className="mt-2 text-slate-500">Browse PDFs, e-books, study materials, and curated links.</p></div><Link to="/digital-resources" className="btn-primary">Explore resources <ArrowRight size={17}/></Link></section></div>
}
