import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { BookOpen } from "lucide-react";
import { supabaseConfigured, supabase } from "../lib/supabase";
import { useAuth } from "../context/AuthContext";

export default function Login() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const navigate=useNavigate(); const { isAdmin }=useAuth();
  async function submit(e){e.preventDefault();setError("");setLoading(true); if(!supabaseConfigured){setError("Connect Supabase first using .env.local.");setLoading(false);return;} const {error}=await supabase.auth.signInWithPassword({email,password}); if(error)setError("Unable to sign in. Check your email and password."); else navigate(email===import.meta.env.VITE_ADMIN_EMAIL&&isAdmin?"/admin":"/"); setLoading(false);}
  return <div className="grid min-h-screen lg:grid-cols-2"><div className="hidden bg-slate-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3 text-xl font-bold"><BookOpen/> College Library</div><div className="mt-24 max-w-xl"><div className="eyebrow text-teal-300">Knowledge access</div><h1 className="mt-4 text-5xl font-black leading-tight">Find the books and resources that move your learning forward.</h1><p className="mt-6 text-lg text-slate-300">A secure, database-driven portal for students and librarians.</p></div></div><div className="text-sm text-slate-400">Library & Digital Resource Management System</div></div><div className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md"><div className="mb-8 lg:hidden"><div className="flex items-center gap-3 text-xl font-bold"><BookOpen/> College Library</div></div><div className="eyebrow">Welcome back</div><h2 className="mt-2 text-3xl font-bold">Sign in</h2><p className="mt-2 text-slate-500">Access your library account.</p>{error&&<div className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="mt-7 space-y-4"><input className="input" type="email" required placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input" type="password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn-primary w-full" disabled={loading}>{loading?"Signing in…":"Sign in"}</button></div><p className="mt-6 text-center text-sm text-slate-500">New student? <Link to="/register" className="font-semibold text-teal-700">Create an account</Link></p><Link to="/" className="mt-4 block text-center text-sm text-slate-400">← Back to home</Link></form></div></div>
}
