import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { supabase } from "../lib/supabase";

export default function Register() {
  const [form,setForm]=useState({full_name:"",email:"",student_id:"",password:""}); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false); const navigate=useNavigate();
  const change=e=>setForm({...form,[e.target.name]:e.target.value});
  async function submit(e){e.preventDefault();setError("");setMessage("");setLoading(true);if(!supabase){setError("Connect Supabase first using .env.local.");setLoading(false);return;}const {data,error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{full_name:form.full_name,student_id:form.student_id}}});if(error)setError(error.message);else{setMessage(data.session?"Account created.":"Account created. Check your email to confirm, then sign in.");if(data.session)navigate("/");}setLoading(false);}
  return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><form onSubmit={submit} className="card w-full max-w-lg p-7"><div className="eyebrow">Student registration</div><h1 className="mt-2 text-3xl font-bold">Create your library account</h1><p className="mt-2 text-sm text-slate-500">New accounts are always created as students.</p>{error&&<div className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{message&&<div className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}<div className="mt-6 grid gap-4 sm:grid-cols-2"><input name="full_name" required className="input sm:col-span-2" placeholder="Full name" value={form.full_name} onChange={change}/><input name="student_id" required className="input" placeholder="Student ID" value={form.student_id} onChange={change}/><input name="email" required type="email" className="input" placeholder="College email" value={form.email} onChange={change}/><input name="password" required minLength={8} type="password" className="input sm:col-span-2" placeholder="Password (8+ characters)" value={form.password} onChange={change}/><button className="btn-primary sm:col-span-2" disabled={loading}>{loading?"Creating…":"Create account"}</button></div><p className="mt-6 text-center text-sm text-slate-500">Already registered? <Link to="/login" className="font-semibold text-teal-700">Sign in</Link></p></form></div>
}
